version: "3"

server:
  command: "php artisan octane:start --server=roadrunner --no-interaction --host=0.0.0.0 --port=8100"
  relay: pipes

http:
  address: 0.0.0.0:8100

  pool:
    num_workers: 8
    max_jobs: 500
    max_worker_memory: 128

static:
  dir: public
  forbid: [".php", ".htaccess"]
