apiVersion: apps/v1
kind: Deployment
metadata:
  name: soursd-api
spec:
  selector:
    matchLabels:
      app: soursd-api
  replicas: 1
  template:
    metadata:
      labels:
        app: soursd-api
    spec:
      containers:
        - name: soursd-api
          image: hdruk/soursd-api:latest
          ports:
            - containerPort: 8100
              name: soursd-api
      dnsPolicy: ClusterFirst