apiVersion: v1
kind: Pod
metadata:
  name: soursd-api
spec:
  selector:
    matchLabels:
      app: soursd-api
  template:
    metadata:
      labels:
        app: soursd-api
  containers:
    - name: soursd-api
      image: hdruk/soursd-api:latest
      ports:
        - containerPort: 8100