<?php

// LS - TODO - This file needs renaming
return [
    /*
    |----------------------------------------------------------------------------------------------------
    | Default entity model config
    |----------------------------------------------------------------------------------------------------
    |
    | These options determine the base entity model configuration for SOURSD
    |
    */
    'entities' => [
        'decision_models' => [
            [
                'name' => 'Sanctions',
                'description' => 'Users and Organisations who are on the UK Sanctions List should not be provided with access to sensitive data.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'sanctions.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
            [
                'name' => 'User location',
                'description' => 'A User should be located in a country which adheres to equivalent data protection law.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'user_location.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
            [
                'name' => 'Organisation due dilligence',
                'description' => 'Additional Organisation due dilligence checks should be carried out on Organisations who are not validated.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'organisation_due_dilligence.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
            [
                'name' => 'Training',
                'description' => 'A User must have completed mandatory training before requesting data access.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'user_training.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An organisation must have Cyber Essentials and ISO27001 accreditations in effect.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'user_training_expiry.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
            [
                'name' => 'Delegate/Key Contact',
                'description' => 'An Organisation must have at least one Delegate/Key Contact to confirm a User\'s behaviour within secure data environments.',
                'entity_model_type_id' => 1,
                'calls_file' => 1,
                'file_path' => 'organisation_delegate.json',
                'calls_operation' => 0,
                'operation' => null,
            ],
        ],
        'user_validation_rules' => [
            [
                'name' => 'Sanctions',
                'description' => 'A User should not appear on the UK sanctions list.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'User location',
                'description' => 'A User is located in a country which has UK equivalent data protection laws.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Identity',
                'description' => 'A User has verified their identity via the Identity Verification Technology (IDVT).',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Training',
                'description' => 'A User has completed the NHS Research Secure Data Environment training.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Training',
                'description' => 'A User has completed the ONS Accredited Researcher training.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Training',
                'description' => 'A User has completed the MRC GDPR training.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'SDE Network',
                'description' => 'A User has signed the NHS Research Secure Data Environment Terms of Use.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'User affiliation',
                'description' => 'A User has been affiliated by a relevant, validated Organisation.',
                'entity_model_type_id' => 2,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
        ],
        'org_validation_rules' => [
            [
                'name' => 'Sanctions',
                'description' => 'An Organisation is not on the UK sanctions list.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has Cyber Essentials certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has Cyber Essentials Plus certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has ISO27001 Accredited certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has either a Cyber Essentials or ISO27001 Accredited certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has either a Cyber Essentials Plus or ISO27001 Accredited certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Data security compliance',
                'description' => 'An Organisation has DSPT certification.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
            [
                'name' => 'Delegate/Key Contact',
                'description' => 'An Organisation has at least one Delegate/Key Contact to affiliate Users.',
                'entity_model_type_id' => 3,
                'calls_file' => 0,
                'file_path' => null,
                'calls_operation' => 1,
                'operation' => '',
            ],
        ],
    ],
];
