apiVersion: v1
kind: Service
metadata:
  name: speedi-as-api
  labels:
    app: speedi-as-api
spec:
  ports:
    - port: 8100
      protocol: "TCP"
      targetPort: 8100
  selector:
    app: speedi-as-api
